// GENERATED from ../../raw/bundles/final.pkg.js [code region] — edit tools/, not this file.
// module: ui/menu.js | units: 3 | span: [2148179,2501267) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u2148 [2148179,2148381) kind=var len=1097
var menuScene,deathScreenScene,menuSceneA,respawnButton,classSelectScene,activeMenuTabScene,shopScene,animateShopSkinFloat,lobbyHomeScene,Mv,menuSceneF,killerAvatarImage,podiumAvatarImage,Mz,matchEndTitleText,matchEndSubtitleText,victoryGhostContainer,gameOverWipeRight,gameOverWipeLeft,gameOverWipeContainer,matchEndBannerRoot,menuBannerImage,menuBackdropImage,menuDimOverlay,menuBackdropWrapper,menuContentWrapper,leaderboardHintText,buildMatchEndBanner,MO,leaderboardEntries,updateDeathScreenHealth,eliminatedByLabel,killerNameLabel,resumeGameButton,settingsPanelView,usernameInputOverlay,homeAdBannerSlot1,homeAdBannerSlot2,menuPlexusBackground,rankHelper,returnToLobbyButton,playAgainButton,matchmakingScene,matchFoundScene,mapSplashScene,menuTabBarScene,menuTabScenes,N7,skinPreviewContainer,readyToggleButton,mobileReloadButton,mobileAimButton,mobileLeftShootButton,mobileRightShootButton,Ne,mobileFireHeld,leftShootHeld,rightShootHeld,weaponPreviewWidget,weaponStatLabels,weaponDetailTitle,weaponIconCache,domOverlayPositioner,deathScreenClassPanel,rankUpBadgeContainer,rankUpOverlayScene;
// __UNIT__ u2239 [2422518,2423312) kind=function len=1313
function layoutChatInput(){var axK=stringDecoderAlias,marginLeft=0x1f,bottomOffset=0x438-0xaa-0xa;bottomOffset=0x96-0x14;menuScene['tGTnWzZUhv']||deathScreenScene['tGTnWzZUhv']?bottomOffset-=0x64:bottomOffset+=0xd;chatInput['style']['marginLeft']=marginLeft/canvasRenderer['aratio']+'px',chatInput[axK(0xa92)][axK(0x903)]=bottomOffset/canvasRenderer['aratio']+'px',chatInput['style'][axK(0xad0)]=chatInputWidth/canvasRenderer[axK(0x10b7)]+'px',chatInput[axK(0xa92)][axK(0x300)]=chatInputHeight/canvasRenderer['aratio']+'px',chatInput['style'][axK(0xb6a)]=chatInputFontSize/canvasRenderer['aratio']+'px',chatInput[axK(0xa92)]['paddingLeft']=chatInputPaddingLeft/canvasRenderer[axK(0x10b7)]+'px',chatInput['style'][axK(0x557)]='rgba(0,0,0,0.28)',homeAdBannerSlot1['x']=canvasRenderer['MBbucSOqeMu']-0x12c/0x2;partyController['GJklRqbLTCs']&&partyController[axK(0x211)]&&partyController['isLeader']&&(homeAdBannerSlot1['x']+=0x1f4);homeAdBannerSlot2['x']=canvasRenderer['MBbucSOqeMu']-0x12c/0x2;partyController['GJklRqbLTCs']&&partyController['AhUnLeUeD']&&partyController[axK(0x1003)]&&(homeAdBannerSlot2['x']+=0x1f4);for(var a3n=0x0;a3n<respawnAdSlots[axK(0x3a2)];a3n++){respawnAdSlots[a3n]['x']=canvasRenderer[axK(0x68b)]+0x12c/0x2,!isCrazyGames&&(respawnAdSlots[a3n]['x']=canvasRenderer[axK(0x68b)]+0x152/0x2);}}
// __UNIT__ u2500 [2501219,2501267) kind=function len=92
function respawnUiReset(){menuScene['ReDNKHkwk']=![],layoutChatInput(),deathFadeTimer=-0x1;}
