// GENERATED from ../../raw/bundles/final.pkg.js [code region] — edit tools/, not this file.
// module: characters/mesh-pool.js | units: 8 | span: [2022375,2734815) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u1800 [2022375,2022762) kind=expr len=782
awpWeaponConfig['ui']=awpWeaponUiConfig,awpWeaponConfig[stringDecoderAlias(0x41e)]=0x1c,awpWeaponConfig['clPJAbVChXM']=0.8,awpWeaponConfig['RrrNzesxY']=0x1,awpWeaponConfig['EZDFHAjrW']=0.7,awpWeaponConfig['xqItLdaOH']=0x3,awpWeaponConfig[stringDecoderAlias(0x109e)]=0x3d,awpWeaponConfig[stringDecoderAlias(0x541)]=0x50,awpWeaponConfig['Cryjoaozcvi']=0x2,awpWeaponConfig[stringDecoderAlias(0x861)]=1.4,awpWeaponConfig['FjQTHXKbTSO']=0xe,awpWeaponConfig['LQyUujxQvU']=0.9,awpWeaponConfig['bloomRecoil']=0.3,awpWeaponConfig['shotBloom']=0.2,awpWeaponConfig['UVCeyZNLZ']=stringDecoderAlias(0x275),awpWeaponConfig[stringDecoderAlias(0x3de)]=0x64,awpWeaponConfig['ZzTdsTSrXT']=0.9,awpWeaponConfig[stringDecoderAlias(0x89a)]=0.23,awpWeaponConfig[stringDecoderAlias(0x752)]=awpSpreadTuning;
// __UNIT__ u2080 [2091032,2091400) kind=expr len=501
partyController[stringDecoderAlias(0xe4c)]=function(){var aqV=stringDecoderAlias;if(partyController['kAYKXUcnTQV']==undefined||!isHttps)return;var a3k=new XMLHttpRequest();a3k['open']('GET','https://matchmaking.de'+aqV(0x971)+aqV(0x64b)),a3k['onload']=function(){var aqW=aqV;!isNaN(a3k['responseText'])&&(partyController[aqW(0xfd)]['text']=a3k[aqW(0xabf)]+'\x20Pla'+aqW(0x110c));},a3k[aqV(0x263)]();},partyController['equippedSkins']=defaultEquippedSkins,partyController[stringDecoderAlias(0xa39)]=[];
// __UNIT__ u2318 [2446068,2446421) kind=function len=567
function removeEntityByIndex(a3l){var ayv=stringDecoderAlias;if(entityList[ayv(0x3a2)]==0x0)return;aimTargetEntity==entityList[a3l]&&(aimTargetEntity=null);if(entityList[a3l]==null)return;recycleMesh(entityList[a3l]["r23ZS3L2g"]);recycledNametagPool['indexOf'](entityList[a3l]['threeNametag'])==-0x1&&(recycledNametagPool[recycledNametagPool['length']]=entityList[a3l]['threeNametag'],entityList[a3l]['threeNametag']['piylfJrZJ'](),entityList[a3l]['threeNametag']=null);var a3m=entityList[ayv(0x3a2)];entityList[a3l]=entityList[a3m-0x1],entityList['length']=a3m-0x1;}
// __UNIT__ u2576 [2515775,2515825) kind=for len=117
for(var loopIndex=0x0;loopIndex<activeMeshPool[stringDecoderAlias(0x3a2)];loopIndex++){activeMeshPool[loopIndex]=[];}
// __UNIT__ u2590 [2519205,2519227) kind=var len=73
var characterMaterialCache=[],recycledMeshPool=[],recycledNametagPool=[];
// __UNIT__ u2591 [2519227,2519438) kind=function len=324
function recycleMesh(a3o){var aAp=stringDecoderAlias;if(a3o==null)return;worldScene['remove'](a3o),activeMixerList[aAp(0xfad)](a3o[aAp(0xee1)])!=-0x1&&activeMixerList[aAp(0x5de)](activeMixerList[aAp(0xfad)](a3o[aAp(0xee1)]),0x1),recycledMeshPool[aAp(0xfad)](a3o)==-0x1&&(recycledMeshPool[recycledMeshPool[aAp(0x3a2)]]=a3o);}
// __UNIT__ u2592 [2519438,2520114) kind=function len=1041
function swapCharacterMesh(charRecord,visualType){var aAq=stringDecoderAlias;if(charRecord["r23ZS3L2g"]==null)return;if(charRecord["r23ZS3L2g"][aAq(0x66c)]==visualType){charRecord['PhbhpxFxPP']==localTeamId&&localTeamId!=0x0?charRecord["r23ZS3L2g"]['PUYitUjkOj']():charRecord["r23ZS3L2g"][aAq(0x632)]();return;}worldScene[aAq(0x944)](charRecord["r23ZS3L2g"]);activeMixerList['indexOf'](charRecord["r23ZS3L2g"]['kDCTWhoSiT'])!=-0x1&&activeMixerList['splice'](activeMixerList['indexOf'](charRecord["r23ZS3L2g"]['kDCTWhoSiT']),0x1);recycleMesh(charRecord[aAq(0xc7e)]);var a3q=charRecord[aAq(0xc7e)];charRecord["r23ZS3L2g"]=createCharacterMesh(![],![],visualType),charRecord[aAq(0x368)]==localTeamId&&localTeamId!=0x0?charRecord[aAq(0xc7e)]['PUYitUjkOj']():charRecord["r23ZS3L2g"]['oRdkBpYPvUp'](),playerSkinsMap[charRecord[aAq(0xd07)]]!=undefined&&partyController['ZgKNqVhpg'](charRecord[aAq(0xc7e)],playerSkinsMap[charRecord['MqaFuSJOX']]),charRecord[aAq(0x69f)]=charRecord[aAq(0xcf8)][weaponStatsTable[weaponOrder[visualType]]['UVCeyZNLZ']];}
// __UNIT__ u2868 [2734412,2734815) kind=if len=527
if(isHttps){var injectedScriptElement=document.createElement('script');injectedScriptElement.async=true;injectedScriptElement.crossOrigin='anonymous';injectedScriptElement.src='https://www.googletagmanager.com/gtag/js?id=UA-87346685-5';function gtag(){dataLayer.push(arguments);}gtag('js',new Date());injectedScriptElement.onload=function(){try{if(gtag!==undefined){gtag('config','G-4T2ZJXRRCK',{cookie_flags:'secure;samesite=none'});}}catch(e){if(!isHttps){console.log(e);}}};document.head.appendChild(injectedScriptElement);}
