// GENERATED from ../../raw/bundles/final.pkg.js [code region] — edit tools/, not this file.
// module: characters/weapon-attach.js | units: 11 | span: [2020161,2677785) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u1768 [2020161,2020289) kind=expr len=215
smgBloomTuning["A8a6k73WsA2"]=0.6,smgBloomTuning['rOXMPlgObCS']=0.35,smgBloomTuning[stringDecoderAlias(0xb88)]=0.25,smgBloomTuning["j0EB3IT4Ug"]=0.3,smgBloomTuning["XQ9Y5sC5x"]=0.07,smgBloomTuning['OUsPgMLOT']=0.05;
// __UNIT__ u1778 [2020583,2020750) kind=expr len=286
smgSpreadTuning[stringDecoderAlias(0xad)]=1.6,smgSpreadTuning['rOXMPlgObCS']=1.2,smgSpreadTuning['still']=0x1,smgSpreadTuning["j0EB3IT4Ug"]=0.15,smgSpreadTuning["XQ9Y5sC5x"]=0.06,smgSpreadTuning['OUsPgMLOT']=0.04,smgSpreadTuning['crouchWalking']=0.85,smgSpreadTuning["W91ldgW19d"]=0.75;
// __UNIT__ u1780 [2020760,2021217) kind=expr len=891
smgWeaponConfig['ui']=smgWeaponUiConfig,smgWeaponConfig['KnpNRhnMD']=2.4,smgWeaponConfig['clPJAbVChXM']=1.2,smgWeaponConfig[stringDecoderAlias(0xe11)]=0.45,smgWeaponConfig[stringDecoderAlias(0x5e3)]=0x1,smgWeaponConfig[stringDecoderAlias(0x2c0)]=0x28,smgWeaponConfig['oCYaTYzkTP']=0x2d,smgWeaponConfig['TgNAHabmu']=0xe,smgWeaponConfig['Cryjoaozcvi']=2.5,smgWeaponConfig[stringDecoderAlias(0xba6)]=0.016,smgWeaponConfig['distanceMinimum']=0.5,smgWeaponConfig['SOtVnhHOG']=1.75*0.75,smgWeaponConfig['FjQTHXKbTSO']=0x2,smgWeaponConfig['OGYwpLBdL']=0x1,smgWeaponConfig['LQyUujxQvU']=0.8,smgWeaponConfig[stringDecoderAlias(0x3a7)]=1.2,smgWeaponConfig['shotBloom']=0.005,smgWeaponConfig[stringDecoderAlias(0x997)]='smg',smgWeaponConfig['QuvgZimFkef']=0x64,smgWeaponConfig[stringDecoderAlias(0x89a)]=0.3,smgWeaponConfig['cGKveZTJVJM']=2.1,smgWeaponConfig[stringDecoderAlias(0x752)]=smgSpreadTuning;
// __UNIT__ u1808 [2022935,2023102) kind=expr len=348
shotgunSpreadTuning["A8a6k73WsA2"]=1.25,shotgunSpreadTuning['rOXMPlgObCS']=0.95,shotgunSpreadTuning[stringDecoderAlias(0xb88)]=0.8,shotgunSpreadTuning[stringDecoderAlias(0x36c)]=0.55,shotgunSpreadTuning["XQ9Y5sC5x"]=0.35,shotgunSpreadTuning['OUsPgMLOT']=0.35,shotgunSpreadTuning[stringDecoderAlias(0x943)]=0.6,shotgunSpreadTuning["W91ldgW19d"]=0.6;
// __UNIT__ u1810 [2023112,2023572) kind=expr len=960
shotgunWeaponConfig['ui']=shotgunWeaponUiConfig,shotgunWeaponConfig['pellets']=0xd,shotgunWeaponConfig['KnpNRhnMD']=0x15,shotgunWeaponConfig['clPJAbVChXM']=0x1,shotgunWeaponConfig[stringDecoderAlias(0xe11)]=0.3,shotgunWeaponConfig['EZDFHAjrW']=0x1,shotgunWeaponConfig[stringDecoderAlias(0x2c0)]=0x2,shotgunWeaponConfig['oCYaTYzkTP']=0x30,shotgunWeaponConfig[stringDecoderAlias(0x541)]=9.5,shotgunWeaponConfig['Cryjoaozcvi']=2.5,shotgunWeaponConfig[stringDecoderAlias(0xba6)]=0.02,shotgunWeaponConfig['distanceMinimum']=0.3,shotgunWeaponConfig['SOtVnhHOG']=1.6*0.7,shotgunWeaponConfig['FjQTHXKbTSO']=0x5,shotgunWeaponConfig[stringDecoderAlias(0x81a)]=0.91,shotgunWeaponConfig['bloomRecoil']=0xd,shotgunWeaponConfig[stringDecoderAlias(0x6bf)]=0.05,shotgunWeaponConfig['UVCeyZNLZ']='shotgun',shotgunWeaponConfig['QuvgZimFkef']=0x64,shotgunWeaponConfig['bloomSpeed']=0.4,shotgunWeaponConfig['cGKveZTJVJM']=2.1,shotgunWeaponConfig['VehNrzoThC']=shotgunSpreadTuning;
// __UNIT__ u2118 [2099599,2099904) kind=function len=495
function postJsonRequest(endpointPath,requestBody,responseCallback){var are=stringDecoderAlias,xhrRequest=new XMLHttpRequest();xhrRequest['open']('POST',loginBaseUrl+endpointPath),xhrRequest['setRequestHeader']('Content-Type','application/json'),xhrRequest[are(0xf53)]=async function(){responseCallback&&responseCallback(xhrRequest['responseText']);},requestBody==undefined&&(requestBody={}),requestBody['idto'+'ken']=partyController['token'],xhrRequest['send'](JSON['stringify'](requestBody));}
// __UNIT__ u2156 [2404498,2405962) kind=expr len=1929
window['onerror']=function(errorMessage,sourceUrl,lineNo,colNo,errorObj){var axh=stringDecoderAlias;errorReportCount++;if(errorReportCount>0xa)return;var errorText='';errorObj!=null?errorText=errorObj['stack']:(errorText=errorMessage,typeof errorText!=axh(0x9ce)&&(errorText=JSON['stringify'](errorMessage)));if(errorText[axh(0xfad)]('Error\x20creating\x20WebGL\x20context')!=-0x1){alert('Error\x20creating\x20WebGL\x20context\x20-\x20Please\x20make\x20sure\x20hardware\x20acceleration\x20is\x20on\x20in\x20your\x20browser\x20settings');return;}if(errorText['indexOf'](axh(0x517)+'bled\x20in\x20current\x20environment.')!=-0x1||errorText[axh(0xfad)]('idpiframe_initialization_failed')!=-0x1){window[axh(0xbb2)]=!![];return;}if(errorText[axh(0xfad)]('Script\x20error.')!=-0x1){window[axh(0xbb2)]=!![],console['log']('You\x27ve\x20encountered\x20a\x20\x27Script\x20error\x27,\x20please\x20send\x20a\x20screenshot\x20of\x20the\x20console\x20to\x20the\x20de'+axh(0xfdf));return;}var ignoredErrorIds=[axh(0x37b),'gcalenpjmijncebpfijmoaglllgpjagf','jinjaccalgkegednnccohejagnlnfdag'];for(var ignoredIdx=0x0;ignoredIdx<ignoredErrorIds['length'];ignoredIdx++){if(errorText['indexOf'](ignoredErrorIds[ignoredIdx])!=-0x1){}}if(isHttps){var errorReportXhr=new XMLHttpRequest();errorReportXhr['open']('POST','https://error.de'+axh(0x1076)),errorReportXhr[axh(0xf88)]('Content-Type','application/json'),errorReportXhr[axh(0xf53)]=function(){};errorText=='{}'&&(errorText='Weird\x20{}\x20error:\x0a'+new Error()['stack']);errorText=JSON['stringify'](reentrancyGuardFlags)+'\x0a'+errorText;var errorReport={};errorReport['version']=clientReportVersion,errorReport[axh(0x240)]=reportNonce,errorReport['error']=errorText,errorReportXhr[axh(0x263)](JSON['stringify'](errorReport));}else{var consoleErrorEntry={};consoleErrorEntry['rnd']=reportNonce,consoleErrorEntry['error']=errorText,console[axh(0xc04)](JSON['stringify'](consoleErrorEntry));}};
// __UNIT__ u2255 [2427432,2428197) kind=function len=1085
function pingRegion(hostPrefix,regionId){var axX=stringDecoderAlias,pingRequest=new XMLHttpRequest();regionPingRequests['push'](pingRequest);var a3o=[0x50,0x1bb];pingRequest[axX(0xdc2)]('POST','https://'+hostPrefix+'_rp.dea'+axX(0x12c)+a3o[Math[axX(0x5ce)](Math[axX(0x4bd)]()*a3o['length'])]+'/rp',!![]),pingRequest['onreadystatechange']=function(){var axY=axX;if(this['readyState']!=0x4)return;if(this[axY(0x99b)]==0xc8){regionPingResponses['push'](hostPrefix);for(var a3p=0x0;a3p<regionPingRequests[axY(0x3a2)];a3p++){regionPingRequests[a3p][axY(0xf8b)]();}var a3q=0x0;for(var a3p=0x0;a3p<regionPingResponses['length'];a3p++){regionPingResponses[a3p]==hostPrefix&&a3q++;}if(a3q>=0x5){clientSettings['region']=regionId;let a3r=!![];settingsPanelView['elem'][axY(0x1040)]==null&&(a3r=![],settingsPanelView[axY(0x8cb)]['appendChild'](settingsPanelView['elem'])),document['getElementById'](axY(0x1a2)+regionId)['onclick'](),!a3r&&settingsPanelView['elem']['remove'](),saveAndApplySettings(),partyController[axY(0xdbd)]();}else pingAllRegions(!![]);}},pingRequest[axX(0x263)]('pingplx');}
// __UNIT__ u2587 [2517101,2518754) kind=function len=1928
function attachWeaponModel(character,weaponName,isFirstPerson,a3r){var aAk=stringDecoderAlias;if(useCompressedRigs&&(isFirstPerson||a3r)){}var a3s=cloneWeaponMesh(weaponName);character[aAk(0x600)]=a3s,a3s['onload']=function(a3u){var aAl=aAk;a3u['XOVWraMIAg'](function(a3y){if(a3y instanceof usvzFuAsEB['Mesh']){}});if(isFirstPerson){var a3v={};a3v[aAl(0x39e)]=a3u;var a3w=applyCharacterShader(a3v,![]);a3u['XOVWraMIAg'](function(a3y){var aAm=aAl;a3y[aAm(0x52e)]!=undefined&&(a3y['material']['uniforms']['squeeze']!=undefined&&(a3y['material']['uniforms'][aAm(0xeb0)][aAm(0x9c5)]=0x1,a3y['material'][aAm(0x29b)]['squeeze']['afCJVYrCGK']=!![],a3y['material']['side']=leftHandedEnabled?usvzFuAsEB['BackSide']:usvzFuAsEB['FrontSide']));});}else{var a3x={};a3x[aAl(0x39e)]=a3u,applyCharacterShader(a3x,![]);}if(isFirstPerson||a3r)return;a3u[rotationKey]['z']=-Math['PI']/0x2,a3u[rotationKey]['x']=-Math['PI']/0xa,a3u[rotationKey]['y']=-Math['PI']/0x8,a3u['position']['z']=-0.35,a3u['position']['x']=-0.05,a3u['position']['y']=0.15,a3u['scale'][aAl(0x4e6)](2.1);if(weaponName=='awp'){}};a3s['loaded']&&a3s['onload'](a3s['children'][0x0]);!isFirstPerson&&!a3r?(weaponName=='awp'&&(a3s[aAk(0xd6)][aAk(0x30f)](0.8),a3s['position']['z']-=0.2,a3s['position']['y']-=0.1),character['oGUsalclTsY']['add'](a3s)):(a3s[aAk(0xd6)]['CNFryyAhIm'](2.35),a3s['rotation']['x']=-Math['PI']/2.05,a3s['rotation']['order']='ZYX',a3s['position']['y']+=0.22,a3s['position']['z']+=0.265,weaponName==aAk(0x2ba)&&(a3s['position']['z']-=0.032,a3s[aAk(0x215)]['y']-=0.03),weaponName=='smg'&&(a3s[aAk(0x215)]['z']-=0.12,a3s[aAk(0x215)]['y']-=0.01),weaponName=='awp'&&isFirstPerson&&(a3s['position']['x']=0.05,a3s[aAk(0x215)]['y']=0.42,a3s['position']['z']=0.265,a3s['rotation']['z']=0.13),character[aAk(0x838)]['add'](a3s));var a3t=new usvzFuAsEB['QTOKQmNlEY']();a3t['position']['z']=0.75,a3t[aAk(0x215)]['y']=0.13,a3s[aAk(0x8da)](a3t),character[aAk(0x2d0)]=a3t;}
// __UNIT__ u2808 [2652259,2653319) kind=function len=1351
function finalizeLoadSession(a3o,a3p){var aD1=stringDecoderAlias,a3q=a3o=='terminal'||a3o==aD1(0x710);if(loadSessionState==null||loadSessionState[aD1(0x942)]||loadSessionState[aD1(0xcfa)]&&!a3q||loadSessionState['finalReported']&&a3q)return;a3p!=undefined&&(loadSessionState['reasonOverride']=a3p);a3q?loadSessionState[aD1(0x7e4)]=!![]:loadSessionState[aD1(0xcfa)]=!![];loadSessionState['timeout']!=null&&(a3q||a3o=='timeout')&&(clearTimeout(loadSessionState['timeout']),loadSessionState['timeout']=null);a3q&&loadSessionState[aD1(0xeb9)]!=null&&(clearTimeout(loadSessionState['hardTimeout']),loadSessionState['hardTimeout']=null);a3q&&loadSessionState['gltfStallTimer']!=null&&(clearTimeout(loadSessionState['gltfStallTimer']),loadSessionState['gltfStallTimer']=null);var a3r=buildMatchmakingReport(a3o||'timeout'),a3s=JSON[aD1(0xc6)](a3r);a3o=='terminal'&&clearMatchmakingTerminalUi(a3r['reason']||a3p||aD1(0x10f0));if(typeof isHttps!=aD1(0xf84)&&isHttps){var a3t='https://error.de'+'adshot.io/matchmaking';if(navigator[aD1(0xf0c)]!=undefined&&typeof Blob!=aD1(0xf84))try{var a3u={};a3u[aD1(0xafb)]='application/json';if(navigator[aD1(0xf0c)](a3t,new Blob([a3s],a3u)))return;}catch(a3w){}try{var a3v=new XMLHttpRequest();a3v[aD1(0xdc2)]('POST',a3t,!![]),a3v['setRequestHeader']('Content-Type','application/json'),a3v[aD1(0x263)](a3s);}catch(a3x){}}}
// __UNIT__ u2833 [2676893,2677785) kind=function len=1182
function spawnGunshotTracer(weaponOwner,aimTarget){var aDU=stringDecoderAlias;if(weaponOwner==null)return;forceMatrixUpdate=!![];var a3z=acquireEffectInstance(aDU(0x4e2));a3z['clPJAbVChXM']=weaponOwner['DMZbIHLgyk'][aDU(0xf68)],a3z[aDU(0x40e)]=weaponOwner[aDU(0x2d5)]['RrrNzesxY'],a3z[aDU(0x40e)]=0.3;if(!a3z[aDU(0x19c)]){forceMatrixUpdate=![];return;}a3z['oZzvWrXBEG']['scale']['y']=0.5;var a3A=weaponOwner["r23ZS3L2g"][aDU(0x5c5)];weaponOwner[aDU(0xc7e)][aDU(0x5c5)]=!![],weaponOwner["r23ZS3L2g"]['tip']['updateMatrixWorld']();var a3B=weaponOwner[aDU(0xc7e)][aDU(0x2d0)],a3C=[weaponOwner[aDU(0xc7e)][aDU(0x2d0)]];while(a3B!=weaponOwner["r23ZS3L2g"]){if(a3B['parent']==undefined){forceMatrixUpdate=![];return;}a3B=a3B[aDU(0x8cb)],a3C[a3C['length']]=a3B;}for(var a3D=a3C['length']-0x1;a3D>=0x0;a3D--){a3C[a3D][aDU(0x1019)](),a3C[a3D]['updateMatrixWorld'](!![]);}weaponOwner["r23ZS3L2g"]['visible']=a3A,muzzleWorldPosition[aDU(0x22e)](weaponOwner[aDU(0xc7e)]['tip']['matrixWorld']);var a3E=0x2;a3z['zaCEeRAJY']=weaponOwner['DMZbIHLgyk'][aDU(0x5e3)];var a3F=orientTracerEffect(a3z,aimTarget,muzzleWorldPosition,muzzleWorldPosition['distanceTo'](aimTarget),a3E);forceMatrixUpdate=![];}
