// GENERATED from ../../raw/bundles/VM9.deob.txt — edit tools/, not this file.
// module: world/modes.js | units: 14 | span: [1463440,2771677) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u0042 [1463440,1463868) kind=expr len=680
basisFormatCodes['cTFETC1']=0x0,basisFormatCodes['cTFETC2']=0x1,basisFormatCodes['cTFBC1']=0x2,basisFormatCodes["cTFBC3"]=0x3,basisFormatCodes["cTFBC4"]=0x4,basisFormatCodes['cTFBC5']=0x5,basisFormatCodes['cTFBC7_M6_OPAQUE_ONLY']=0x6,basisFormatCodes['cTFBC7_M5']=0x7,basisFormatCodes['cTFPVRTC1_4_RGB']=0x8,basisFormatCodes['cTFPVRTC1_4_RGBA']=0x9,basisFormatCodes["cTFASTC_4x4"]=0xa,basisFormatCodes['cTFATC_RGB']=0xb,basisFormatCodes['cTFATC_RGBA_INTERPOLATED_ALPHA']=0xc,basisFormatCodes["cTFRGBA32"]=0xd,basisFormatCodes['cTFRGB565']=0xe,basisFormatCodes['cTFBGR565']=0xf,basisFormatCodes["cTFRGBA4444"]=0x10,usvzFuAsEB["BasisTextureLoader"]["BASIS_FORMAT"]=basisFormatCodes;
// __UNIT__ u0146 [1640065,1640343) kind=var len=276
var fpsMeter={startTime:0,frameNumber:0,getFPS:function(){this.frameNumber++;var d=new Date().getTime(),elapsedSec=(d-this.startTime)/1000,result=Math.floor(this.frameNumber/elapsedSec);if(elapsedSec>1){this.startTime=new Date().getTime();this.frameNumber=0;}return result;}};
// __UNIT__ u0388 [1891908,1891954) kind=expr len=90
controlsSettingsCategory['id']="FRF6r51VY32",controlsSettingsCategory['label']='CONTROLS';
// __UNIT__ u1711 [2058167,2058218) kind=var len=141
var perfCountersAlias=perfCounterMap,perfCounterKeys=Object["keys"](perfCountersAlias),frameDeltaMs=0x0,reentrancyGuardFlags={},modeNames={};
// __UNIT__ u1712 [2058218,2058535) kind=expr len=380
modeNames["FFA"]="Free-For-All",modeNames['TDM']="Team Deathmatch",modeNames["SWAT"]='SWAT\x20-\x20Aim\x20for\x20the\x20head!',modeNames['Arcade']='FFA\x20with\x20items',modeNames["Siphon"]='Siphon\x20-\x20Heal\x20on\x20kill',modeNames["Point"]='Hardpoint',modeNames['Confirm']='Kill\x20Confirmed',modeNames['Team\x20KC']='Team\x20Kill\x20Confirmed',modeNames['Dom']="Domination";
// __UNIT__ u1713 [2058535,2058697) kind=var len=238
var modeDisplayNames=modeNames,modeOrder=Object["keys"](modeDisplayNames),mapPool=['tf',"industry",'winter','newmlab','manor',"neon"],modePool=["FFA",'TDM',"Point",'Confirm',"Team KC","Dom"],matchTimeOptions=[0x5,0xa,0x14],regionTable={};
// __UNIT__ u1714 [2058697,2058803) kind=expr len=151
regionTable['2']='North\x20America',regionTable['9']='Europe',regionTable['52']="Asia",regionTable['40']="South America",regionTable['35']="Australia";
// __UNIT__ u2067 [2140644,2140664) kind=expr len=33
partyController['JVLNyGFRGl']={};
// __UNIT__ u2068 [2140664,2140908) kind=for len=303
for(var loopIndex=0x0;loopIndex<weaponOrder['length'];loopIndex++){let a3i=0x8,a3j={};a3j['image']=document["createElement"]('canvas'),a3j['borderedImage']=document['createElement']('canvas'),a3j["noBorder"]=document['createElement']('canvas'),partyController['JVLNyGFRGl'][weaponOrder[loopIndex]]=a3j;}
// __UNIT__ u2181 [2461714,2461981) kind=expr len=341
logDebugPosition=function(){var axq=stringDecoderAlias,a3l=localPlayer['position']["clone"]()['OpiuFvBcQd'](0xa)['round']()['divideScalar'](0xa)['KkKRLGFtA'](),a3m={};a3m['x']=a3l['x'],a3m['y']=a3l['y'],a3m['z']=a3l['z'],a3m['rx']=templatesLive['FRF6r51VY32']['x'],a3m['ry']=templatesLive['FRF6r51VY32']['y'],debugPositionLog["push"](a3m);};
// __UNIT__ u2258 [2480599,2480785) kind=expr len=312
rawMouseSetting["type"]=0x2,rawMouseSetting['id']='rawmouse',rawMouseSetting['text']='Raw\x20Mouse\x20Input:',rawMouseSetting['category']="FRF6r51VY32",rawMouseSetting["default"]=!![],rawMouseSetting['PNiTcTcLjni']=[],rawMouseSetting['onchange']=function(a3l){unadjustedMovement=a3l,ignoreDeathLookSpikes=!![];};
// __UNIT__ u2260 [2480795,2480976) kind=expr len=329
inverseMouseSetting['type']=0x2,inverseMouseSetting['id']='inversemouse',inverseMouseSetting["text"]='Inverse\x20Mouse\x20Y:',inverseMouseSetting['category']='FRF6r51VY32',inverseMouseSetting['default']=![],inverseMouseSetting['PNiTcTcLjni']=[],inverseMouseSetting['onchange']=function(isChecked){inverseMouseEnabled=isChecked;};
// __UNIT__ u2841 [2741383,2742034) kind=function len=930
function playCharacterAnim(animatedChar,nextAnim,fadeDuration,forceRestart){var aE0=stringDecoderAlias;if(animatedChar['currentAnim']==nextAnim&&(forceRestart==undefined||forceRestart==![]))return![];!fadeDuration&&(fadeDuration=0.2);animatedChar['currentAnim']==animatedChar["deathAnim"]&&(fadeDuration=0x0);var a3B=animatedChar['kDCTWhoSiT']['_actions'],a3C=animatedChar['kDCTWhoSiT']['_nActiveActions'],a3D=animatedChar['kDCTWhoSiT']['_bindings'],activeBindingCount=animatedChar['kDCTWhoSiT']['_nActiveBindings'];animatedChar['kDCTWhoSiT']["_nActiveActions"]=0x0,animatedChar['kDCTWhoSiT']['_nActiveBindings']=0x0;for(var a3F=0x0;a3F!==a3C;++a3F){a3B[a3F]["reset"]();}for(var a3F=0x0;a3F!==activeBindingCount;++a3F){a3D[a3F]['useCount']=0x0;}return nextAnim["weight"]=0x1,nextAnim['fadeIn'](fadeDuration),nextAnim['play'](),nextAnim==animatedChar['jumpFP']&&(nextAnim['weight']=0.65),animatedChar['currentAnim']=nextAnim,!![];}
// __UNIT__ u2859 [2770783,2771677) kind=function len=1207
function updateAnimMixers(){var aEd=stringDecoderAlias;if(activeMixerList["length"]>0x0||mapContentGroup["mixers"]["length"]>0x0){var a3y=animDeltaClock["getDelta"]();animDeltaSec=a3y;for(let a3A=0x0;a3A<activeMixerList['length'];a3A++){if(!activeMixerList[a3A]["ReDNKHkwk"]){activeMixerList[a3A]['lVVKDdZusl']=![];continue;}var a3z=0x1;if(localWeaponRig["r23ZS3L2g"]!=undefined){if(activeMixerList[a3A]!=localWeaponRig["r23ZS3L2g"]['kDCTWhoSiT']){if(frameCounter%a3z!=0x0)continue;}else!localPlayer["d2J6H770A10"]&&(localWeaponRig["r23ZS3L2g"]["currentAnim"]==localWeaponRig["r23ZS3L2g"]['aimAnimFP']&&localPlayer["vQ5Ra371n0"]&&(localWeaponRig["r23ZS3L2g"]["currentAnim"]['timeScale']=localPlayer["aZRZkcgAvk"]*0x14+0.3,localPlayer["DMZbIHLgyk"]!=undefined&&localPlayer["DMZbIHLgyk"]['ZzTdsTSrXT']!=undefined&&(localWeaponRig["r23ZS3L2g"]["currentAnim"]['timeScale']*=localPlayer["DMZbIHLgyk"]['ZzTdsTSrXT'])));}!activeMixerList[a3A]["lVVKDdZusl"]&&(a3z=0x3e8,activeMixerList[a3A]['lVVKDdZusl']=!![]),activeMixerList[a3A]['update'](a3y*1.05*transitionFadeFactor*a3z);}for(let a3B=0x0;a3B<mapContentGroup['mixers']['length'];a3B++){mapContentGroup['mixers'][a3B]['update'](a3y*0.7*transitionFadeFactor);}}}
