// GENERATED from ../../raw/bundles/VM9.deob.txt — edit tools/, not this file.
// module: ui/menu.js | units: 5 | span: [1897931,2554096) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u0409 [1897931,1899616) kind=function len=2393
function buildSettingsPanel(settingsItems){var apl=stringDecoderAlias;let a3j=document['createElement']('div');settingsRootDiv=a3j,a3j['id']="settingsDiv",a3j['style']['zIndex']=0x64,a3j['style']["position"]="fixed",a3j['style']['opacity']=0x0,a3j['style']['visibility']='hidden',a3j['style']['display']="none",document["body"]["appendChild"](a3j),a3j['innerHTML']='',settingsPagesContainer=document["createElement"]('div'),settingsPagesContainer['className']='settings-pages',settingsScrollContainer=parseHtmlTemplate("<div class='settings-scroll'><div class='settings-list'></div></div>"),settingsListElement=settingsScrollContainer["children"][0x0],settingsPagesContainer["appendChild"](settingsScrollContainer),a3j['appendChild'](settingsPagesContainer),setupSettingsScroll(settingsScrollContainer,settingsListElement),settingsValueMap={},settingsDefinitions=settingsItems,settingsSections={},activeSettingsCategory=undefined,settingsScrollLockUntil=0x0;var a3k={};settingsItems['forEach'](function(settingDef,itemIndex){var apm=apl;if(!settingDef['ReDNKHkwk'])return;if(settingDef['hideFromMain'])return;var sectionView=settingDef['category']||(settingDef['mobileOnly']?'mobile':'general'),a3s=createSettingRow(settingDef);if(a3s==null)return;a3s['classList']["add"]("settings-row"),a3s['style']['padding']='9px',a3s['style']['paddingLeft']=a3s['style']['paddingRight']="30px",a3s['style']['margin']="0px",a3k[sectionView]==undefined&&(a3k[sectionView]=[]),a3k[sectionView]['push'](a3s);});function a3l(a3p){var apn=apl,a3q=a3k[a3p];if(a3q==undefined||a3q["length"]==0x0)return;var a3r=getOrCreateSettingsSection(a3p,getSettingsCategoryLabel(a3p));for(var a3s=0x0;a3s<a3q["length"];a3s++){a3s%0x2==0x1&&(a3q[a3s]['style']['backgroundColor']='rgba(\x20255,\x20255,\x20255,\x200.03\x20)'),a3r['content']['appendChild'](a3q[a3s]),a3s<a3q["length"]-0x1&&a3r["content"]["appendChild"](parseHtmlTemplate("<div class='bar'></div>"));}refreshScrollbar(settingsScrollContainer,settingsListElement);}for(var a3m=0x0;a3m<platformOptionList['length'];a3m++){a3l(platformOptionList[a3m]['id']);}var a3n=Object['keys'](a3k);for(var a3m=0x0;a3m<a3n['length'];a3m++){a3l(a3n[a3m]);}collectSettingsValues(),initSettingsSliders(),initCustomSelects();var a3o=Object['keys'](settingsSections);a3o["length"]>0x0&&window['showSettingsCategory'](settingsSections["general"]!=undefined?'general':a3o[0x0],!![]);}
// __UNIT__ u2148 [2201477,2201679) kind=var len=1097
var menuScene,deathScreenScene,menuSceneA,respawnButton,classSelectScene,activeMenuTabScene,shopScene,animateShopSkinFloat,lobbyHomeScene,Mv,menuSceneF,killerAvatarImage,podiumAvatarImage,Mz,matchEndTitleText,matchEndSubtitleText,victoryGhostContainer,gameOverWipeRight,gameOverWipeLeft,gameOverWipeContainer,matchEndBannerRoot,menuBannerImage,menuBackdropImage,menuDimOverlay,menuBackdropWrapper,menuContentWrapper,leaderboardHintText,buildMatchEndBanner,MO,leaderboardEntries,updateDeathScreenHealth,eliminatedByLabel,killerNameLabel,resumeGameButton,settingsPanelView,usernameInputOverlay,homeAdBannerSlot1,homeAdBannerSlot2,menuPlexusBackground,rankHelper,returnToLobbyButton,playAgainButton,matchmakingScene,matchFoundScene,mapSplashScene,menuTabBarScene,menuTabScenes,N7,skinPreviewContainer,readyToggleButton,mobileReloadButton,mobileAimButton,mobileLeftShootButton,mobileRightShootButton,Ne,mobileFireHeld,leftShootHeld,rightShootHeld,weaponPreviewWidget,weaponStatLabels,weaponDetailTitle,weaponIconCache,domOverlayPositioner,deathScreenClassPanel,rankUpBadgeContainer,rankUpOverlayScene;
// __UNIT__ u2239 [2474754,2475537) kind=function len=1302
function layoutChatInput(){var axK=stringDecoderAlias,marginLeft=0x1f,bottomOffset=0x438-0xaa-0xa;bottomOffset=0x96-0x14;menuScene['tGTnWzZUhv']||deathScreenScene['tGTnWzZUhv']?bottomOffset-=0x64:bottomOffset+=0xd;chatInput['style']['marginLeft']=marginLeft/canvasRenderer['aratio']+'px',chatInput["style"]["bottom"]=bottomOffset/canvasRenderer['aratio']+'px',chatInput['style']["width"]=chatInputWidth/canvasRenderer["aratio"]+'px',chatInput["style"]["height"]=chatInputHeight/canvasRenderer['aratio']+'px',chatInput['style']["fontSize"]=chatInputFontSize/canvasRenderer['aratio']+'px',chatInput["style"]['paddingLeft']=chatInputPaddingLeft/canvasRenderer["aratio"]+'px',chatInput['style']["backgroundColor"]='rgba(0,0,0,0.28)',homeAdBannerSlot1['x']=canvasRenderer['MBbucSOqeMu']-0x12c/0x2;partyController['GJklRqbLTCs']&&partyController["AhUnLeUeD"]&&partyController['isLeader']&&(homeAdBannerSlot1['x']+=0x1f4);homeAdBannerSlot2['x']=canvasRenderer['MBbucSOqeMu']-0x12c/0x2;partyController['GJklRqbLTCs']&&partyController['AhUnLeUeD']&&partyController["isLeader"]&&(homeAdBannerSlot2['x']+=0x1f4);for(var a3n=0x0;a3n<respawnAdSlots["length"];a3n++){respawnAdSlots[a3n]['x']=canvasRenderer["siccypZlKyH"]+0x12c/0x2,!isCrazyGames&&(respawnAdSlots[a3n]['x']=canvasRenderer["siccypZlKyH"]+0x152/0x2);}}
// __UNIT__ u2268 [2490809,2491504) kind=expr len=1146
applyClientSettings=function(a3l){var ayg=stringDecoderAlias;clientSettings==undefined&&(clientSettings=a3l);var a3m=Object["keys"](a3l);for(var a3n=0x0;a3n<a3m['length'];a3n++){var a3o=a3m[a3n];clientSettings[a3o]=a3l[a3o];}clientSettings['version']=clientSettingsVersion,settingsDebounceTimer=0xc8;},window['getSettingValue']=function(settingsUpdate){var ayh=stringDecoderAlias;if(clientSettings!=undefined&&clientSettings[settingsUpdate]!=undefined)return clientSettings[settingsUpdate];for(var settingKeys=0x0;settingKeys<settingsOptions['length'];settingKeys++){if(settingsOptions[settingKeys]['id']==settingsUpdate)return settingsOptions[settingKeys]["default"];}},window['updateSettingValue']=function(a3l,a3m){var ayi=stringDecoderAlias,a3n={};a3n[a3l]=a3m,applyClientSettings(a3n);for(var a3o=0x0;a3o<settingsOptions["length"];a3o++){if(settingsOptions[a3o]['id']==a3l){settingsOptions[a3o]["default"]=a3m;settingsOptions[a3o]['onchange']!=undefined&&settingsOptions[a3o]["onchange"](a3m);return;}}},buildSettingsPanel(settingsOptions),settingsPanelView=new domOverlayPositioner(document['getElementById']("settingsDiv"),0xc8,0x78,1.25);
// __UNIT__ u2500 [2554048,2554096) kind=function len=92
function respawnUiReset(){menuScene['ReDNKHkwk']=![],layoutChatInput(),deathFadeTimer=-0x1;}
