// GENERATED from ../../raw/bundles/final.pkg.js [code region] — edit tools/, not this file.
// module: core/bitfield.js | units: 15 | span: [2019970,2493341) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u1764 [2019970,2019980) kind=var len=20
var bitMaskArray=[];
// __UNIT__ u1765 [2019980,2020046) kind=for len=119
for(var loopIndex=0x0;loopIndex<0x20;loopIndex++){bitMaskArray[stringDecoderAlias(0xf1e)](Math['pow'](0x2,loopIndex));}
// __UNIT__ u1834 [2027096,2027462) kind=function len=412
function makeBaseInputState(){var aql=stringDecoderAlias,a3i={};return a3i['up']=![],a3i['down']=![],a3i[aql(0xed8)]=![],a3i[aql(0xff3)]=![],a3i[aql(0xee4)]=![],a3i[aql(0x692)]=![],a3i['OUsPgMLOT']=![],a3i["hRdQS9697"]=![],a3i[aql(0xdff)]=![],a3i['name']='zBgadyCVYk',a3i['copy']=function(a3j){var a3k=bitsetDefinitions[this['name']];for(var a3l=0x0;a3l<a3k['length'];a3l++){this[a3k[a3l]]=a3j[a3k[a3l]];}},a3i;}
// __UNIT__ u1838 [2027999,2028023) kind=var len=99
var bitsetDefinitions={},bitsetStateMakers=[makeBaseInputState,makeAnimState,makePlayerStateFlags];
// __UNIT__ u1839 [2028023,2028226) kind=for len=452
for(var loopIndex=0x0;loopIndex<bitsetStateMakers['length'];loopIndex++){var cachedPlayerRef=new bitsetStateMakers[loopIndex](),HX=getObjectKeys(cachedPlayerRef);globalKeyList[stringDecoderAlias(0x5de)](globalKeyList[stringDecoderAlias(0xfad)]('name'),0x1),globalKeyList[stringDecoderAlias(0xfad)](stringDecoderAlias(0x609))!=-0x1&&globalKeyList['splice'](globalKeyList['indexOf']('copy'),0x1),bitsetDefinitions[cachedPlayerRef['name']]=globalKeyList;}
// __UNIT__ u1840 [2028226,2028371) kind=function len=200
function encodeInputBitset(a3i){var aqo=stringDecoderAlias,a3j=0x0,a3k=bitsetDefinitions[a3i[aqo(0x9ec)]];for(var a3l=0x0;a3l<a3k['length'];a3l++){a3i[a3k[a3l]]&&(a3j+=bitMaskArray[a3l]);}return a3j;}
// __UNIT__ u1841 [2028371,2028508) kind=function len=279
function decodeInputBitset(targetObj,bitmask){var fieldNames=bitsetDefinitions[targetObj['name']];for(var fieldIndex=0x0;fieldIndex<fieldNames['length'];fieldIndex++){bitmask&bitMaskArray[fieldIndex]?targetObj[fieldNames[fieldIndex]]=!![]:targetObj[fieldNames[fieldIndex]]=![];}}
// __UNIT__ u1849 [2028935,2029127) kind=expr len=497
messageTemplateId['tdkZouYda']=uint8TypeCode,messageTemplateId[stringDecoderAlias(0xdaf)]=float32TypeCode,messageTemplateId['uBHZYKAHa']=float32TypeCode,messageTemplateId[stringDecoderAlias(0xc14)]=float32TypeCode,messageTemplateId['TCHdFFAXmk']=uint8TypeCode,messageTemplateId['ibyXzJIMNf']=uint8TypeCode,messageTemplateId['YSmEAVINAh']=INT_TWO,messageTemplateId['wGiOzKcGlnH']=uint8TypeCode,messageTemplateId['hkhrYayXI']=uint8TypeCode,messageTemplateId[stringDecoderAlias(0x749)]=uint8TypeCode;
// __UNIT__ u1861 [2029285,2029418) kind=expr len=374
messageTemplateIj['pMwSuGipfE']=float32TypeCode,messageTemplateIj[stringDecoderAlias(0xce6)]=float32TypeCode,messageTemplateIj[stringDecoderAlias(0xdaf)]=float64TypeCode,messageTemplateIj['uBHZYKAHa']=float64TypeCode,messageTemplateIj['AHPhtLFTi']=float64TypeCode,messageTemplateIj[stringDecoderAlias(0x308)]=float64TypeCode,messageTemplateIj['MHnEcbTxpbz']=float64TypeCode;
// __UNIT__ u1863 [2029428,2029564) kind=expr len=321
messageTemplateIk['JoHdvmpcMvL']=float32TypeCode,messageTemplateIk['uBHZYKAHa']=float32TypeCode,messageTemplateIk['yxEKoSFAg']=float32TypeCode,messageTemplateIk['AHPhtLFTi']=INT_ONE,messageTemplateIk[stringDecoderAlias(0x308)]=INT_ONE,messageTemplateIk['MHnEcbTxpbz']=INT_ONE,messageTemplateIk['tdkZouYda']=uint8TypeCode;
// __UNIT__ u1865 [2029574,2029631) kind=expr len=137
messageTemplateIl['tdkZouYda']=uint8TypeCode,messageTemplateIl['uBHZYKAHa']=float32TypeCode,messageTemplateIl['MfCOcfVUx']=uint8TypeCode;
// __UNIT__ u1869 [2029669,2029768) kind=expr len=235
fieldTypeMapIn['lDKzyZxhKX']=uint8TypeCode,fieldTypeMapIn['wtZUXNpiCWl']=uint8TypeCode,fieldTypeMapIn['JoHdvmpcMvL']=float32TypeCode,fieldTypeMapIn['uBHZYKAHa']=float32TypeCode,fieldTypeMapIn[stringDecoderAlias(0xc14)]=float32TypeCode;
// __UNIT__ u1923 [2031582,2031659) kind=expr len=196
messageTemplateIo['xJXXoGTVwzq']=INT_ONE,messageTemplateIo[stringDecoderAlias(0xdaf)]=float32TypeCode,messageTemplateIo['uBHZYKAHa']=float32TypeCode,messageTemplateIo['yxEKoSFAg']=float32TypeCode;
// __UNIT__ u2317 [2445162,2446068) kind=expr len=1559
partyController['SsysxYnEEx']=function(){var ayt=stringDecoderAlias;if(loadedPlayerRigCount<0x4){console['log'](ayt(0xcd6));return;}if(crazyGamesGame==undefined||!![]){startMatchmaking();return;}if(matchmakingActive)return;crazyGamesGame['addEventListener'](ayt(0xeb7),muteVolumeForAd),crazyGamesGame[ayt(0xa9a)]('adFinished',handleAdFinished),crazyGamesGame['addEventListener'](ayt(0xd3c),handleAdFinished),crazyGamesGame[ayt(0x9e2)]('midga'+'me');},partyController[stringDecoderAlias(0xe1b)]=function(){var ayu=stringDecoderAlias,a3l=bitsetDefinitions[liveKeyState['name']];for(var a3m=0x0;a3m<a3l[ayu(0x3a2)];a3m++){if(movementKeyNames[ayu(0xfad)](a3l[a3m])!=-0x1)continue;liveKeyState[a3l[a3m]]=![];}if(localWeaponRig==undefined)return![];for(var a3m=0x0;a3m<0x3;a3m++){if(weaponModelSlots[a3m]==undefined)return![];}return templatesLive['B20L372s8']['v']=0x64,templatesLive[ayu(0xaaa)]['eXABYtRfN']=partyController[ayu(0xd07)],templatesLive['B20L372s8'][ayu(0xd69)]=!![],networkSendEnabled&&gameWebSocket!=null&&gameWebSocket['readyState']==0x1&&(encodeMessage(templatesLive[ayu(0xaaa)],classSelectPacketView),gameWebSocket['send'](classSelectPacketBuffer)),classSelectScene['ReDNKHkwk']=![],classSelectScene['tGTnWzZUhv']=![],adsZoomInterpolator['t']=0x1,adsZoomInterpolator[ayu(0xa45)]=adsZoomMin,adsZoomInterpolator['yYemIMQjxq']=adsZoomMin,currentAimSensitivity=aimSensitivityUnit*baseAimSensitivity,worldCamera['cGKveZTJVJM']+=0.01,partyController['ybKMeoEjyk']=![],mobileFireHeld=![],leftShootHeld=![],rightShootHeld=![],ignoreNextTouch=![],!![];};
// __UNIT__ u2476 [2492646,2493341) kind=function len=916
function initEffectPositionTracking(targetEntity){var azJ=stringDecoderAlias;targetEntity["zkT2rWLY297"]=new usvzFuAsEB['gURkzCzeY'](),targetEntity["b152tm12ro9"]=new usvzFuAsEB['gURkzCzeY'](),targetEntity['yoghpvfQE']=new usvzFuAsEB['gURkzCzeY'](),targetEntity['setPosition']=function(a3p){var azI=decodeString;targetEntity[azI(0x215)]['copy'](a3p),targetEntity[azI(0x5f3)][azI(0x609)](a3p),targetEntity[azI(0x564)]['copy'](a3p);},targetEntity[azJ(0x17e)]=function(a3p){targetEntity['position']['fromArray'](a3p),targetEntity['setPosition'](targetEntity['position']);},targetEntity['NGSMBcCHUv']=function(a3p,a3q){var azK=azJ;targetEntity[azK(0x215)]['setComponent'](a3p,targetEntity['position'][azK(0xa8)](a3p)+a3q),targetEntity[azK(0x5f3)][azK(0x106f)](a3p,targetEntity["zkT2rWLY297"]['getComponent'](a3p)+a3q),targetEntity[azK(0x564)]['setComponent'](a3p,targetEntity["b152tm12ro9"]['getComponent'](a3p)+a3q);};}
