// GENERATED from ../../raw/bundles/final.pkg.js [code region] — edit tools/, not this file.
// module: sim/physics.js | units: 4 | span: [2417573,2462281) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u2215 [2417573,2417625) kind=expr len=101
emptyCollisionWorld[stringDecoderAlias(0xbac)]=undefined,emptyCollisionWorld['fkXbORMTcl']=undefined;
// __UNIT__ u2217 [2417635,2418246) kind=function len=1013
function simulatePhysics(deltaTime){var axC=stringDecoderAlias;updateActiveShakes(deltaTime);for(var tweenIndex=0x0;tweenIndex<activeTweenList[axC(0x3a2)];tweenIndex++){var tweenEntry=activeTweenList['array'][tweenIndex];tweenEntry['IUTkaCQgos']+=deltaTime;if(tweenEntry['IUTkaCQgos']<tweenEntry['delay'])continue;if(tweenEntry['IUTkaCQgos']>tweenEntry['delay']+tweenEntry['time']){tweenEntry['obj'][tweenEntry[axC(0xc1a)]]=tweenEntry[axC(0x2bb)];tweenEntry['cb']!=undefined&&(tweenEntry['cb'](tweenEntry[axC(0x9a0)]),tweenEntry['cb']=null);activeTweenList[axC(0x18f)][tweenIndex]==tweenEntry&&(recycleTween(activeTweenList[axC(0x18f)][tweenIndex]),activeTweenList['splice'](tweenIndex,0x1));tweenIndex--;continue;}var tweenProgress=(tweenEntry[axC(0xe31)]-tweenEntry[axC(0xe2d)])/tweenEntry['time'];tweenEntry['obj'][tweenEntry[axC(0xc1a)]]=lerpValue(tweenEntry[axC(0x37d)],tweenEntry['newp'],tweenEntry['ef'](tweenProgress)),tweenEntry["KWC92ef2Y9"]!=undefined&&tweenEntry[axC(0x553)](tweenEntry[axC(0x9a0)]);}}
// __UNIT__ u2258 [2428411,2428598) kind=expr len=358
rawMouseSetting[stringDecoderAlias(0xafb)]=0x2,rawMouseSetting['id']='rawmouse',rawMouseSetting['text']='Raw\x20Mouse\x20Input:',rawMouseSetting['category']=stringDecoderAlias(0x124),rawMouseSetting[stringDecoderAlias(0xe5)]=!![],rawMouseSetting['PNiTcTcLjni']=[],rawMouseSetting['onchange']=function(a3l){unadjustedMovement=a3l,ignoreDeathLookSpikes=!![];};
// __UNIT__ u2362 [2461361,2462281) kind=function len=1605
function recoilRecovery(deltaTime){var ayH=stringDecoderAlias;menuCinematicCamera['time']+=deltaTime;menuCinematicCamera[ayH(0xbc2)]>=cinematicShotList['length']&&(menuCinematicCamera[ayH(0xbc2)]=0x0);menuCinematicCamera[ayH(0x35c)]>cinematicShotList[menuCinematicCamera[ayH(0xbc2)]]['time']&&(menuCinematicCamera[ayH(0xbc2)]++,menuCinematicCamera[ayH(0xbc2)]>=cinematicShotList['length']&&(menuCinematicCamera['onScene']=0x0),menuCinematicCamera[ayH(0x35c)]=0x0);let currentScene=cinematicShotList[menuCinematicCamera[ayH(0xbc2)]];var sceneProgress=menuCinematicCamera['time']/currentScene['time'];for(var axisIndex=0x0;axisIndex<0x3;axisIndex++){menuCinematicCamera['position']['setComponent'](axisIndex,lerpValue(currentScene['start']['position'][ayH(0xa8)](axisIndex),currentScene['end']['position']['getComponent'](axisIndex),sceneProgress)),menuCinematicCamera['lookingAt'][ayH(0x106f)](axisIndex,lerpValue(currentScene['start'][ayH(0xf5f)][ayH(0xa8)](axisIndex),currentScene['end']['JoIkrtRxhZ']['getComponent'](axisIndex),sceneProgress));}menuCinematicCamera[ayH(0xf5f)](menuCinematicCamera['lookingAt']),menuCinematicCamera['mPDLPePIID']();var fadeOpacity=Math['min'](currentScene['time']-menuCinematicCamera[ayH(0x35c)],menuCinematicCamera['time'])/0x1f4;isSafari&&(fadeOpacity=0x1),fadeOpacity=clampValue(fadeOpacity,0.1,0x1)*0.65,!partyController['sRhDBwlFm']?webglRenderer['domElement']['style']['opacity']!=0x0&&(webglRenderer[ayH(0xfa1)][ayH(0xa92)]['opacity']=0x0):webglRenderer['domElement']['style'][ayH(0x40e)]!=fadeOpacity&&(webglRenderer[ayH(0xfa1)]['style']['opacity']=fadeOpacity);}
