// GENERATED from ../../raw/bundles/VM9.deob.txt — edit tools/, not this file.
// module: characters/mesh-pool.js | units: 9 | span: [1893457,2789991) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u0404 [1893457,1894705) kind=function len=1756
function setupSettingsScroll(linkedElem,scrollContainer){var apa=stringDecoderAlias;if(linkedElem==undefined||scrollContainer==undefined||scrollContainer['settingsScrollReady'])return;scrollContainer['settingsScrollReady']=!![];var lastTouchY=0x0,touchScrolling=![];function a3m(a3r){var ap9=decodeString;if(a3r==undefined)return![];var a3s=a3r["tagName"];return a3s=='INPUT'||a3s=="BUTTON"||a3s=='SELECT'||a3s=="TEXTAREA"||a3s=='LABEL';}var a3n={};a3n["passive"]=![],scrollContainer["addEventListener"]("wheel",function(a3r){var apb=apa;if(scrollContainer['scrollHeight']<=scrollContainer["clientHeight"])return;scrollContainer["scrollTop"]+=a3r['deltaY'],refreshScrollbar(linkedElem,scrollContainer),a3r['preventDefault'](),a3r['stopPropagation']();},a3n),scrollContainer["addEventListener"]("scroll",function(){refreshScrollbar(linkedElem,scrollContainer),scrollContainer===settingsListElement&&syncActiveSettingsCategory();});var a3o={};a3o['passive']=![],scrollContainer['addEventListener']('touchstart',function(a3r){var apc=apa;touchScrolling=!a3m(a3r['target'])&&a3r["changedTouches"]["length"]>0x0,touchScrolling&&(lastTouchY=a3r["changedTouches"][0x0]["clientY"],a3r["stopPropagation"]());},a3o);var a3p={};a3p["passive"]=![],scrollContainer["addEventListener"]('touchmove',function(a3r){if(!touchScrolling||a3r['changedTouches']['length']==0x0)return;var a3s=a3r['changedTouches'][0x0]['clientY'];scrollContainer['scrollTop']+=lastTouchY-a3s,lastTouchY=a3s,refreshScrollbar(linkedElem,scrollContainer),a3r['preventDefault'](),a3r['stopPropagation']();},a3p);var touchendOpts={};touchendOpts['passive']=![],scrollContainer['addEventListener']('touchend',function(){touchScrolling=![];},touchendOpts),refreshScrollbar(linkedElem,scrollContainer);}
// __UNIT__ u1800 [2074634,2075030) kind=expr len=671
awpWeaponConfig['ui']=awpWeaponUiConfig,awpWeaponConfig["KnpNRhnMD"]=0x1c,awpWeaponConfig['clPJAbVChXM']=0.8,awpWeaponConfig['RrrNzesxY']=0x1,awpWeaponConfig['EZDFHAjrW']=0.7,awpWeaponConfig['xqItLdaOH']=0x3,awpWeaponConfig["oCYaTYzkTP"]=0x3d,awpWeaponConfig["TgNAHabmu"]=0x50,awpWeaponConfig['Cryjoaozcvi']=0x2,awpWeaponConfig["SOtVnhHOG"]=1.4,awpWeaponConfig['FjQTHXKbTSO']=0xe,awpWeaponConfig['LQyUujxQvU']=0.9,awpWeaponConfig['bloomRecoil']=0.3,awpWeaponConfig['shotBloom']=0.2,awpWeaponConfig['UVCeyZNLZ']="sniper",awpWeaponConfig["QuvgZimFkef"]=0x64,awpWeaponConfig['ZzTdsTSrXT']=0.9,awpWeaponConfig["bloomSpeed"]=0.23,awpWeaponConfig["VehNrzoThC"]=awpSpreadTuning;
// __UNIT__ u2080 [2144019,2144401) kind=expr len=485
partyController["yhtfGGmyFf"]=function(){var aqV=stringDecoderAlias;if(partyController['kAYKXUcnTQV']==undefined||!isHttps)return;var a3k=new XMLHttpRequest();a3k['open']('GET','https://matchmaking.de'+"adshot.io/pla"+"yercount"),a3k['onload']=function(){var aqW=aqV;!isNaN(a3k['responseText'])&&(partyController["kAYKXUcnTQV"]['text']=a3k["responseText"]+'\x20Pla'+"yers Online");},a3k["send"]();},partyController['equippedSkins']=defaultEquippedSkins,partyController["aMWaisFtZ"]=[];
// __UNIT__ u2318 [2498655,2499004) kind=function len=563
function removeEntityByIndex(a3l){var ayv=stringDecoderAlias;if(entityList["length"]==0x0)return;aimTargetEntity==entityList[a3l]&&(aimTargetEntity=null);if(entityList[a3l]==null)return;recycleMesh(entityList[a3l]["r23ZS3L2g"]);recycledNametagPool['indexOf'](entityList[a3l]['threeNametag'])==-0x1&&(recycledNametagPool[recycledNametagPool['length']]=entityList[a3l]['threeNametag'],entityList[a3l]['threeNametag']['piylfJrZJ'](),entityList[a3l]['threeNametag']=null);var a3m=entityList["length"];entityList[a3l]=entityList[a3m-0x1],entityList['length']=a3m-0x1;}
// __UNIT__ u2576 [2568786,2568834) kind=for len=100
for(var loopIndex=0x0;loopIndex<activeMeshPool["length"];loopIndex++){activeMeshPool[loopIndex]=[];}
// __UNIT__ u2590 [2572218,2572240) kind=var len=73
var characterMaterialCache=[],recycledMeshPool=[],recycledNametagPool=[];
// __UNIT__ u2591 [2572240,2572448) kind=function len=321
function recycleMesh(a3o){var aAp=stringDecoderAlias;if(a3o==null)return;worldScene['remove'](a3o),activeMixerList["indexOf"](a3o["kDCTWhoSiT"])!=-0x1&&activeMixerList["splice"](activeMixerList["indexOf"](a3o["kDCTWhoSiT"]),0x1),recycledMeshPool["indexOf"](a3o)==-0x1&&(recycledMeshPool[recycledMeshPool["length"]]=a3o);}
// __UNIT__ u2592 [2572448,2573136) kind=function len=1053
function swapCharacterMesh(charRecord,visualType){var aAq=stringDecoderAlias;if(charRecord["r23ZS3L2g"]==null)return;if(charRecord["r23ZS3L2g"]["visualType"]==visualType){charRecord['PhbhpxFxPP']==localTeamId&&localTeamId!=0x0?charRecord["r23ZS3L2g"]['PUYitUjkOj']():charRecord["r23ZS3L2g"]["oRdkBpYPvUp"]();return;}worldScene["remove"](charRecord["r23ZS3L2g"]);activeMixerList['indexOf'](charRecord["r23ZS3L2g"]['kDCTWhoSiT'])!=-0x1&&activeMixerList['splice'](activeMixerList['indexOf'](charRecord["r23ZS3L2g"]['kDCTWhoSiT']),0x1);recycleMesh(charRecord["r23ZS3L2g"]);var a3q=charRecord["r23ZS3L2g"];charRecord["r23ZS3L2g"]=createCharacterMesh(![],![],visualType),charRecord["PhbhpxFxPP"]==localTeamId&&localTeamId!=0x0?charRecord["r23ZS3L2g"]['PUYitUjkOj']():charRecord["r23ZS3L2g"]['oRdkBpYPvUp'](),playerSkinsMap[charRecord["MqaFuSJOX"]]!=undefined&&partyController['ZgKNqVhpg'](charRecord["r23ZS3L2g"],playerSkinsMap[charRecord['MqaFuSJOX']]),charRecord["gunshot"]=charRecord["ydlqCbKiBtk"][weaponStatsTable[weaponOrder[visualType]]['UVCeyZNLZ']];}
// __UNIT__ u2868 [2789588,2789991) kind=if len=527
if(isHttps){var injectedScriptElement=document.createElement('script');injectedScriptElement.async=true;injectedScriptElement.crossOrigin='anonymous';injectedScriptElement.src='https://www.googletagmanager.com/gtag/js?id=UA-87346685-5';function gtag(){dataLayer.push(arguments);}gtag('js',new Date());injectedScriptElement.onload=function(){try{if(gtag!==undefined){gtag('config','G-4T2ZJXRRCK',{cookie_flags:'secure;samesite=none'});}}catch(e){if(!isHttps){console.log(e);}}};document.head.appendChild(injectedScriptElement);}
