// GENERATED from ../../raw/bundles/VM9.deob.txt — edit tools/, not this file.
// module: characters/weapon-attach.js | units: 14 | span: [2072391,2732591) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u1768 [2072391,2072516) kind=expr len=197
smgBloomTuning["A8a6k73WsA2"]=0.6,smgBloomTuning['rOXMPlgObCS']=0.35,smgBloomTuning["still"]=0.25,smgBloomTuning["j0EB3IT4Ug"]=0.3,smgBloomTuning["XQ9Y5sC5x"]=0.07,smgBloomTuning['OUsPgMLOT']=0.05;
// __UNIT__ u1778 [2072800,2072971) kind=expr len=275
smgSpreadTuning["A8a6k73WsA2"]=1.6,smgSpreadTuning['rOXMPlgObCS']=1.2,smgSpreadTuning['still']=0x1,smgSpreadTuning["j0EB3IT4Ug"]=0.15,smgSpreadTuning["XQ9Y5sC5x"]=0.06,smgSpreadTuning['OUsPgMLOT']=0.04,smgSpreadTuning['crouchWalking']=0.85,smgSpreadTuning["W91ldgW19d"]=0.75;
// __UNIT__ u1780 [2072981,2073455) kind=expr len=788
smgWeaponConfig['ui']=smgWeaponUiConfig,smgWeaponConfig['KnpNRhnMD']=2.4,smgWeaponConfig['clPJAbVChXM']=1.2,smgWeaponConfig["RrrNzesxY"]=0.45,smgWeaponConfig["EZDFHAjrW"]=0x1,smgWeaponConfig["xqItLdaOH"]=0x28,smgWeaponConfig['oCYaTYzkTP']=0x2d,smgWeaponConfig['TgNAHabmu']=0xe,smgWeaponConfig['Cryjoaozcvi']=2.5,smgWeaponConfig["distanceEffect"]=0.016,smgWeaponConfig['distanceMinimum']=0.5,smgWeaponConfig['SOtVnhHOG']=1.75*0.75,smgWeaponConfig['FjQTHXKbTSO']=0x2,smgWeaponConfig['OGYwpLBdL']=0x1,smgWeaponConfig['LQyUujxQvU']=0.8,smgWeaponConfig["bloomRecoil"]=1.2,smgWeaponConfig['shotBloom']=0.005,smgWeaponConfig["UVCeyZNLZ"]='smg',smgWeaponConfig['QuvgZimFkef']=0x64,smgWeaponConfig["bloomSpeed"]=0.3,smgWeaponConfig['cGKveZTJVJM']=2.1,smgWeaponConfig["VehNrzoThC"]=smgSpreadTuning;
// __UNIT__ u1788 [2073629,2073801) kind=expr len=268
arSpreadTuning["A8a6k73WsA2"]=1.75,arSpreadTuning["rOXMPlgObCS"]=1.25,arSpreadTuning["still"]=0.95,arSpreadTuning["j0EB3IT4Ug"]=0.5,arSpreadTuning["XQ9Y5sC5x"]=0.02,arSpreadTuning["OUsPgMLOT"]=0.015,arSpreadTuning["crouchWalking"]=0.6,arSpreadTuning["W91ldgW19d"]=0.5;
// __UNIT__ u1790 [2073811,2074284) kind=expr len=763
arWeaponConfig['ui']=arWeaponUiConfig,arWeaponConfig['KnpNRhnMD']=3.2,arWeaponConfig["clPJAbVChXM"]=0x1,arWeaponConfig["RrrNzesxY"]=0.6,arWeaponConfig['EZDFHAjrW']=0x1,arWeaponConfig["xqItLdaOH"]=0x1e,arWeaponConfig['oCYaTYzkTP']=0x33,arWeaponConfig['TgNAHabmu']=0xb,arWeaponConfig['Cryjoaozcvi']=3.55,arWeaponConfig['distanceEffect']=0x0,arWeaponConfig['distanceMinimum']=0x1,arWeaponConfig['SOtVnhHOG']=1.6*0.75,arWeaponConfig["FjQTHXKbTSO"]=0x2,arWeaponConfig['OGYwpLBdL']=2.6,arWeaponConfig["LQyUujxQvU"]=0.94,arWeaponConfig['bloomRecoil']=0.02,arWeaponConfig['shotBloom']=0.02,arWeaponConfig["UVCeyZNLZ"]="scar",arWeaponConfig['QuvgZimFkef']=0x64,arWeaponConfig['bloomSpeed']=0.6,arWeaponConfig["cGKveZTJVJM"]=2.5,arWeaponConfig["VehNrzoThC"]=arSpreadTuning;
// __UNIT__ u1798 [2074458,2074624) kind=expr len=270
awpSpreadTuning["A8a6k73WsA2"]=2.5,awpSpreadTuning["rOXMPlgObCS"]=1.5,awpSpreadTuning['still']=1.5,awpSpreadTuning["j0EB3IT4Ug"]=0.8,awpSpreadTuning["XQ9Y5sC5x"]=0x0,awpSpreadTuning["OUsPgMLOT"]=0x0,awpSpreadTuning['crouchWalking']=1.2,awpSpreadTuning["W91ldgW19d"]=0x1;
// __UNIT__ u1808 [2075196,2075367) kind=expr len=307
shotgunSpreadTuning["A8a6k73WsA2"]=1.25,shotgunSpreadTuning['rOXMPlgObCS']=0.95,shotgunSpreadTuning["still"]=0.8,shotgunSpreadTuning["j0EB3IT4Ug"]=0.55,shotgunSpreadTuning["XQ9Y5sC5x"]=0.35,shotgunSpreadTuning['OUsPgMLOT']=0.35,shotgunSpreadTuning["crouchWalking"]=0.6,shotgunSpreadTuning["W91ldgW19d"]=0.6;
// __UNIT__ u1810 [2075377,2075849) kind=expr len=882
shotgunWeaponConfig['ui']=shotgunWeaponUiConfig,shotgunWeaponConfig['pellets']=0xd,shotgunWeaponConfig['KnpNRhnMD']=0x15,shotgunWeaponConfig['clPJAbVChXM']=0x1,shotgunWeaponConfig["RrrNzesxY"]=0.3,shotgunWeaponConfig['EZDFHAjrW']=0x1,shotgunWeaponConfig["xqItLdaOH"]=0x2,shotgunWeaponConfig['oCYaTYzkTP']=0x30,shotgunWeaponConfig["TgNAHabmu"]=9.5,shotgunWeaponConfig['Cryjoaozcvi']=2.5,shotgunWeaponConfig["distanceEffect"]=0.02,shotgunWeaponConfig['distanceMinimum']=0.3,shotgunWeaponConfig['SOtVnhHOG']=1.6*0.7,shotgunWeaponConfig['FjQTHXKbTSO']=0x5,shotgunWeaponConfig["LQyUujxQvU"]=0.91,shotgunWeaponConfig['bloomRecoil']=0xd,shotgunWeaponConfig["shotBloom"]=0.05,shotgunWeaponConfig['UVCeyZNLZ']='shotgun',shotgunWeaponConfig['QuvgZimFkef']=0x64,shotgunWeaponConfig['bloomSpeed']=0.4,shotgunWeaponConfig['cGKveZTJVJM']=2.1,shotgunWeaponConfig['VehNrzoThC']=shotgunSpreadTuning;
// __UNIT__ u2118 [2152612,2152915) kind=function len=493
function postJsonRequest(endpointPath,requestBody,responseCallback){var are=stringDecoderAlias,xhrRequest=new XMLHttpRequest();xhrRequest['open']('POST',loginBaseUrl+endpointPath),xhrRequest['setRequestHeader']('Content-Type','application/json'),xhrRequest["onload"]=async function(){responseCallback&&responseCallback(xhrRequest['responseText']);},requestBody==undefined&&(requestBody={}),requestBody['idto'+'ken']=partyController['token'],xhrRequest['send'](JSON['stringify'](requestBody));}
// __UNIT__ u2156 [2456449,2457972) kind=expr len=1988
window['onerror']=function(errorMessage,sourceUrl,lineNo,colNo,errorObj){var axh=stringDecoderAlias;errorReportCount++;if(errorReportCount>0xa)return;var errorText='';errorObj!=null?errorText=errorObj['stack']:(errorText=errorMessage,typeof errorText!="string"&&(errorText=JSON['stringify'](errorMessage)));if(errorText["indexOf"]('Error\x20creating\x20WebGL\x20context')!=-0x1){alert('Error\x20creating\x20WebGL\x20context\x20-\x20Please\x20make\x20sure\x20hardware\x20acceleration\x20is\x20on\x20in\x20your\x20browser\x20settings');return;}if(errorText['indexOf']("Cookies are not ena"+'bled\x20in\x20current\x20environment.')!=-0x1||errorText["indexOf"]('idpiframe_initialization_failed')!=-0x1){window["loginDisabled"]=!![];return;}if(errorText["indexOf"]('Script\x20error.')!=-0x1){window["loginDisabled"]=!![],console['log']('You\x27ve\x20encountered\x20a\x20\x27Script\x20error\x27,\x20please\x20send\x20a\x20screenshot\x20of\x20the\x20console\x20to\x20the\x20de'+"adshot.io discord, thank you!");return;}var ignoredErrorIds=["dhdgffkkebhmkfjojejmpbldmpobfkfo",'gcalenpjmijncebpfijmoaglllgpjagf','jinjaccalgkegednnccohejagnlnfdag'];for(var ignoredIdx=0x0;ignoredIdx<ignoredErrorIds['length'];ignoredIdx++){if(errorText['indexOf'](ignoredErrorIds[ignoredIdx])!=-0x1){}}if(isHttps){var errorReportXhr=new XMLHttpRequest();errorReportXhr['open']('POST','https://error.de'+"adshot.io/error"),errorReportXhr["setRequestHeader"]('Content-Type','application/json'),errorReportXhr["onload"]=function(){};errorText=='{}'&&(errorText='Weird\x20{}\x20error:\x0a'+new Error()['stack']);errorText=JSON['stringify'](reentrancyGuardFlags)+'\x0a'+errorText;var errorReport={};errorReport['version']=clientReportVersion,errorReport["rnd"]=reportNonce,errorReport['error']=errorText,errorReportXhr["send"](JSON['stringify'](errorReport));}else{var consoleErrorEntry={};consoleErrorEntry['rnd']=reportNonce,consoleErrorEntry['error']=errorText,console["log"](JSON['stringify'](consoleErrorEntry));}};
// __UNIT__ u2255 [2479640,2480385) kind=function len=1065
function pingRegion(hostPrefix,regionId){var axX=stringDecoderAlias,pingRequest=new XMLHttpRequest();regionPingRequests['push'](pingRequest);var a3o=[0x50,0x1bb];pingRequest["open"]('POST','https://'+hostPrefix+'_rp.dea'+"dshot.io:"+a3o[Math["floor"](Math["random"]()*a3o['length'])]+'/rp',!![]),pingRequest['onreadystatechange']=function(){var axY=axX;if(this['readyState']!=0x4)return;if(this["status"]==0xc8){regionPingResponses['push'](hostPrefix);for(var a3p=0x0;a3p<regionPingRequests["length"];a3p++){regionPingRequests[a3p]["abort"]();}var a3q=0x0;for(var a3p=0x0;a3p<regionPingResponses['length'];a3p++){regionPingResponses[a3p]==hostPrefix&&a3q++;}if(a3q>=0x5){clientSettings['region']=regionId;let a3r=!![];settingsPanelView['elem']["parentNode"]==null&&(a3r=![],settingsPanelView["parent"]['appendChild'](settingsPanelView['elem'])),document['getElementById']("region."+regionId)['onclick'](),!a3r&&settingsPanelView['elem']['remove'](),saveAndApplySettings(),partyController["hBqACvqzO"]();}else pingAllRegions(!![]);}},pingRequest["send"]('pingplx');}
// __UNIT__ u2587 [2570128,2571756) kind=function len=1903
function attachWeaponModel(character,weaponName,isFirstPerson,a3r){var aAk=stringDecoderAlias;if(useCompressedRigs&&(isFirstPerson||a3r)){}var a3s=cloneWeaponMesh(weaponName);character["wpn"]=a3s,a3s['onload']=function(a3u){var aAl=aAk;a3u['XOVWraMIAg'](function(a3y){if(a3y instanceof usvzFuAsEB['Mesh']){}});if(isFirstPerson){var a3v={};a3v["scene"]=a3u;var a3w=applyCharacterShader(a3v,![]);a3u['XOVWraMIAg'](function(a3y){var aAm=aAl;a3y["material"]!=undefined&&(a3y['material']['uniforms']['squeeze']!=undefined&&(a3y['material']['uniforms']["squeeze"]["value"]=0x1,a3y['material']["uniforms"]['squeeze']['afCJVYrCGK']=!![],a3y['material']['side']=leftHandedEnabled?usvzFuAsEB['BackSide']:usvzFuAsEB['FrontSide']));});}else{var a3x={};a3x["scene"]=a3u,applyCharacterShader(a3x,![]);}if(isFirstPerson||a3r)return;a3u[rotationKey]['z']=-Math['PI']/0x2,a3u[rotationKey]['x']=-Math['PI']/0xa,a3u[rotationKey]['y']=-Math['PI']/0x8,a3u['position']['z']=-0.35,a3u['position']['x']=-0.05,a3u['position']['y']=0.15,a3u['scale']["CNFryyAhIm"](2.1);if(weaponName=='awp'){}};a3s['loaded']&&a3s['onload'](a3s['children'][0x0]);!isFirstPerson&&!a3r?(weaponName=='awp'&&(a3s["scale"]["OpiuFvBcQd"](0.8),a3s['position']['z']-=0.2,a3s['position']['y']-=0.1),character['oGUsalclTsY']['add'](a3s)):(a3s["scale"]['CNFryyAhIm'](2.35),a3s['rotation']['x']=-Math['PI']/2.05,a3s['rotation']['order']='ZYX',a3s['position']['y']+=0.22,a3s['position']['z']+=0.265,weaponName=="shotgun"&&(a3s['position']['z']-=0.032,a3s["position"]['y']-=0.03),weaponName=='smg'&&(a3s["position"]['z']-=0.12,a3s["position"]['y']-=0.01),weaponName=='awp'&&isFirstPerson&&(a3s['position']['x']=0.05,a3s["position"]['y']=0.42,a3s['position']['z']=0.265,a3s['rotation']['z']=0.13),character["uMpvMUJct"]['add'](a3s));var a3t=new usvzFuAsEB['QTOKQmNlEY']();a3t['position']['z']=0.75,a3t["position"]['y']=0.13,a3s["add"](a3t),character["tip"]=a3t;}
// __UNIT__ u2808 [2706547,2707611) kind=function len=1355
function finalizeLoadSession(a3o,a3p){var aD1=stringDecoderAlias,a3q=a3o=='terminal'||a3o=="complete";if(loadSessionState==null||loadSessionState["completed"]||loadSessionState["reported"]&&!a3q||loadSessionState['finalReported']&&a3q)return;a3p!=undefined&&(loadSessionState['reasonOverride']=a3p);a3q?loadSessionState["finalReported"]=!![]:loadSessionState["reported"]=!![];loadSessionState['timeout']!=null&&(a3q||a3o=='timeout')&&(clearTimeout(loadSessionState['timeout']),loadSessionState['timeout']=null);a3q&&loadSessionState["hardTimeout"]!=null&&(clearTimeout(loadSessionState['hardTimeout']),loadSessionState['hardTimeout']=null);a3q&&loadSessionState['gltfStallTimer']!=null&&(clearTimeout(loadSessionState['gltfStallTimer']),loadSessionState['gltfStallTimer']=null);var a3r=buildMatchmakingReport(a3o||'timeout'),a3s=JSON["stringify"](a3r);a3o=='terminal'&&clearMatchmakingTerminalUi(a3r['reason']||a3p||"terminal");if(typeof isHttps!="undefined"&&isHttps){var a3t='https://error.de'+'adshot.io/matchmaking';if(navigator["sendBeacon"]!=undefined&&typeof Blob!="undefined")try{var a3u={};a3u["type"]='application/json';if(navigator["sendBeacon"](a3t,new Blob([a3s],a3u)))return;}catch(a3w){}try{var a3v=new XMLHttpRequest();a3v["open"]('POST',a3t,!![]),a3v['setRequestHeader']('Content-Type','application/json'),a3v["send"](a3s);}catch(a3x){}}}
// __UNIT__ u2833 [2731695,2732591) kind=function len=1186
function spawnGunshotTracer(weaponOwner,aimTarget){var aDU=stringDecoderAlias;if(weaponOwner==null)return;forceMatrixUpdate=!![];var a3z=acquireEffectInstance("T1P0J19B02U");a3z['clPJAbVChXM']=weaponOwner['DMZbIHLgyk']["clPJAbVChXM"],a3z["opacity"]=weaponOwner["DMZbIHLgyk"]['RrrNzesxY'],a3z["opacity"]=0.3;if(!a3z["oZzvWrXBEG"]){forceMatrixUpdate=![];return;}a3z['oZzvWrXBEG']['scale']['y']=0.5;var a3A=weaponOwner["r23ZS3L2g"]["visible"];weaponOwner["r23ZS3L2g"]["visible"]=!![],weaponOwner["r23ZS3L2g"]['tip']['updateMatrixWorld']();var a3B=weaponOwner["r23ZS3L2g"]["tip"],a3C=[weaponOwner["r23ZS3L2g"]["tip"]];while(a3B!=weaponOwner["r23ZS3L2g"]){if(a3B['parent']==undefined){forceMatrixUpdate=![];return;}a3B=a3B["parent"],a3C[a3C['length']]=a3B;}for(var a3D=a3C['length']-0x1;a3D>=0x0;a3D--){a3C[a3D]["updateMatrix"](),a3C[a3D]['updateMatrixWorld'](!![]);}weaponOwner["r23ZS3L2g"]['visible']=a3A,muzzleWorldPosition["TLgJbfmniE"](weaponOwner["r23ZS3L2g"]['tip']['matrixWorld']);var a3E=0x2;a3z['zaCEeRAJY']=weaponOwner['DMZbIHLgyk']["EZDFHAjrW"];var a3F=orientTracerEffect(a3z,aimTarget,muzzleWorldPosition,muzzleWorldPosition['distanceTo'](aimTarget),a3E);forceMatrixUpdate=![];}
