// GENERATED from ../../raw/bundles/VM9.deob.txt — edit tools/, not this file.
// module: sim/physics.js | units: 3 | span: [2469916,2514803) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u2215 [2469916,2469970) kind=expr len=88
emptyCollisionWorld["RNQDluasaN"]=undefined,emptyCollisionWorld['fkXbORMTcl']=undefined;
// __UNIT__ u2217 [2469980,2470559) kind=function len=981
function simulatePhysics(deltaTime){var axC=stringDecoderAlias;updateActiveShakes(deltaTime);for(var tweenIndex=0x0;tweenIndex<activeTweenList["length"];tweenIndex++){var tweenEntry=activeTweenList['array'][tweenIndex];tweenEntry['IUTkaCQgos']+=deltaTime;if(tweenEntry['IUTkaCQgos']<tweenEntry['delay'])continue;if(tweenEntry['IUTkaCQgos']>tweenEntry['delay']+tweenEntry['time']){tweenEntry['obj'][tweenEntry["param"]]=tweenEntry["newp"];tweenEntry['cb']!=undefined&&(tweenEntry['cb'](tweenEntry["obj"]),tweenEntry['cb']=null);activeTweenList["array"][tweenIndex]==tweenEntry&&(recycleTween(activeTweenList["array"][tweenIndex]),activeTweenList['splice'](tweenIndex,0x1));tweenIndex--;continue;}var tweenProgress=(tweenEntry["IUTkaCQgos"]-tweenEntry["delay"])/tweenEntry['time'];tweenEntry['obj'][tweenEntry["param"]]=lerpValue(tweenEntry["old"],tweenEntry['newp'],tweenEntry['ef'](tweenProgress)),tweenEntry["KWC92ef2Y9"]!=undefined&&tweenEntry["KWC92ef2Y9"](tweenEntry["obj"]);}}
// __UNIT__ u2362 [2513884,2514803) kind=function len=1604
function recoilRecovery(deltaTime){var ayH=stringDecoderAlias;menuCinematicCamera['time']+=deltaTime;menuCinematicCamera["onScene"]>=cinematicShotList['length']&&(menuCinematicCamera["onScene"]=0x0);menuCinematicCamera["time"]>cinematicShotList[menuCinematicCamera["onScene"]]['time']&&(menuCinematicCamera["onScene"]++,menuCinematicCamera["onScene"]>=cinematicShotList['length']&&(menuCinematicCamera['onScene']=0x0),menuCinematicCamera["time"]=0x0);let currentScene=cinematicShotList[menuCinematicCamera["onScene"]];var sceneProgress=menuCinematicCamera['time']/currentScene['time'];for(var axisIndex=0x0;axisIndex<0x3;axisIndex++){menuCinematicCamera['position']['setComponent'](axisIndex,lerpValue(currentScene['start']['position']["getComponent"](axisIndex),currentScene['end']['position']['getComponent'](axisIndex),sceneProgress)),menuCinematicCamera['lookingAt']["setComponent"](axisIndex,lerpValue(currentScene['start']["JoIkrtRxhZ"]["getComponent"](axisIndex),currentScene['end']['JoIkrtRxhZ']['getComponent'](axisIndex),sceneProgress));}menuCinematicCamera["JoIkrtRxhZ"](menuCinematicCamera['lookingAt']),menuCinematicCamera['mPDLPePIID']();var fadeOpacity=Math['min'](currentScene['time']-menuCinematicCamera["time"],menuCinematicCamera['time'])/0x1f4;isSafari&&(fadeOpacity=0x1),fadeOpacity=clampValue(fadeOpacity,0.1,0x1)*0.65,!partyController['sRhDBwlFm']?webglRenderer['domElement']['style']['opacity']!=0x0&&(webglRenderer["domElement"]["style"]['opacity']=0x0):webglRenderer['domElement']['style']["opacity"]!=fadeOpacity&&(webglRenderer["domElement"]['style']['opacity']=fadeOpacity);}
