// GENERATED from ../../raw/bundles/VM9.deob.txt — edit tools/, not this file.
// module: core/bitfield.js | units: 16 | span: [2072204,2546213) (interleaved; exact ranges are per-unit markers below)
// emission order within this file follows global order (sorted by start); rebundle with: node tools/bundle.mjs
// __UNIT__ u1764 [2072204,2072214) kind=var len=20
var bitMaskArray=[];
// __UNIT__ u1765 [2072214,2072276) kind=for len=100
for(var loopIndex=0x0;loopIndex<0x20;loopIndex++){bitMaskArray["push"](Math['pow'](0x2,loopIndex));}
// __UNIT__ u1834 [2079330,2079691) kind=function len=407
function makeBaseInputState(){var aql=stringDecoderAlias,a3i={};return a3i['up']=![],a3i['down']=![],a3i["left"]=![],a3i["right"]=![],a3i["space"]=![],a3i["HpsuHliFMHL"]=![],a3i['OUsPgMLOT']=![],a3i["hRdQS9697"]=![],a3i["MFUoomFzxq"]=![],a3i['name']='zBgadyCVYk',a3i['copy']=function(a3j){var a3k=bitsetDefinitions[this['name']];for(var a3l=0x0;a3l<a3k['length'];a3l++){this[a3k[a3l]]=a3j[a3k[a3l]];}},a3i;}
// __UNIT__ u1838 [2080224,2080248) kind=var len=99
var bitsetDefinitions={},bitsetStateMakers=[makeBaseInputState,makeAnimState,makePlayerStateFlags];
// __UNIT__ u1839 [2080248,2080443) kind=for len=384
for(var loopIndex=0x0;loopIndex<bitsetStateMakers['length'];loopIndex++){var cachedPlayerRef=new bitsetStateMakers[loopIndex](),HX=getObjectKeys(cachedPlayerRef);globalKeyList["splice"](globalKeyList["indexOf"]('name'),0x1),globalKeyList["indexOf"]("copy")!=-0x1&&globalKeyList['splice'](globalKeyList['indexOf']('copy'),0x1),bitsetDefinitions[cachedPlayerRef['name']]=globalKeyList;}
// __UNIT__ u1840 [2080443,2080584) kind=function len=196
function encodeInputBitset(a3i){var aqo=stringDecoderAlias,a3j=0x0,a3k=bitsetDefinitions[a3i["name"]];for(var a3l=0x0;a3l<a3k['length'];a3l++){a3i[a3k[a3l]]&&(a3j+=bitMaskArray[a3l]);}return a3j;}
// __UNIT__ u1841 [2080584,2080721) kind=function len=279
function decodeInputBitset(targetObj,bitmask){var fieldNames=bitsetDefinitions[targetObj['name']];for(var fieldIndex=0x0;fieldIndex<fieldNames['length'];fieldIndex++){bitmask&bitMaskArray[fieldIndex]?targetObj[fieldNames[fieldIndex]]=!![]:targetObj[fieldNames[fieldIndex]]=![];}}
// __UNIT__ u1849 [2081145,2081344) kind=expr len=459
messageTemplateId['tdkZouYda']=uint8TypeCode,messageTemplateId["JoHdvmpcMvL"]=float32TypeCode,messageTemplateId['uBHZYKAHa']=float32TypeCode,messageTemplateId["yxEKoSFAg"]=float32TypeCode,messageTemplateId['TCHdFFAXmk']=uint8TypeCode,messageTemplateId['ibyXzJIMNf']=uint8TypeCode,messageTemplateId['YSmEAVINAh']=INT_TWO,messageTemplateId['wGiOzKcGlnH']=uint8TypeCode,messageTemplateId['hkhrYayXI']=uint8TypeCode,messageTemplateId["qXuHmlbSlxE"]=uint8TypeCode;
// __UNIT__ u1861 [2081505,2081646) kind=expr len=337
messageTemplateIj['pMwSuGipfE']=float32TypeCode,messageTemplateIj["VqpNEuOqqCX"]=float32TypeCode,messageTemplateIj["JoHdvmpcMvL"]=float64TypeCode,messageTemplateIj['uBHZYKAHa']=float64TypeCode,messageTemplateIj['AHPhtLFTi']=float64TypeCode,messageTemplateIj["mGOwFesuTt"]=float64TypeCode,messageTemplateIj['MHnEcbTxpbz']=float64TypeCode;
// __UNIT__ u1863 [2081656,2081794) kind=expr len=308
messageTemplateIk['JoHdvmpcMvL']=float32TypeCode,messageTemplateIk['uBHZYKAHa']=float32TypeCode,messageTemplateIk['yxEKoSFAg']=float32TypeCode,messageTemplateIk['AHPhtLFTi']=INT_ONE,messageTemplateIk["mGOwFesuTt"]=INT_ONE,messageTemplateIk['MHnEcbTxpbz']=INT_ONE,messageTemplateIk['tdkZouYda']=uint8TypeCode;
// __UNIT__ u1865 [2081804,2081861) kind=expr len=137
messageTemplateIl['tdkZouYda']=uint8TypeCode,messageTemplateIl['uBHZYKAHa']=float32TypeCode,messageTemplateIl['MfCOcfVUx']=uint8TypeCode;
// __UNIT__ u1869 [2081900,2082000) kind=expr len=221
fieldTypeMapIn['lDKzyZxhKX']=uint8TypeCode,fieldTypeMapIn['wtZUXNpiCWl']=uint8TypeCode,fieldTypeMapIn['JoHdvmpcMvL']=float32TypeCode,fieldTypeMapIn['uBHZYKAHa']=float32TypeCode,fieldTypeMapIn["yxEKoSFAg"]=float32TypeCode;
// __UNIT__ u1875 [2082072,2082462) kind=expr len=1006
messageTemplateIq['loEhMkBVEme']=uint8TypeCode,messageTemplateIq['JoHdvmpcMvL']=float32TypeCode,messageTemplateIq["uBHZYKAHa"]=float32TypeCode,messageTemplateIq['yxEKoSFAg']=float32TypeCode,messageTemplateIq['zjSptXbZfA']=float32TypeCode,messageTemplateIq["QoYwfvDUd"]=float32TypeCode,messageTemplateIq['ULHoUFJiqo']=float32TypeCode,messageTemplateIq['BMflnUjRv']=float32TypeCode,messageTemplateIq['pTWaJQCQIlk']=float32TypeCode,messageTemplateIq['KUkUYkavzt']=float32TypeCode,messageTemplateIq['bdyycxmjR']=float32TypeCode,messageTemplateIq['gPEUHGwIpHk']=float32TypeCode,messageTemplateIq["GDSucbCLAxr"]=float32TypeCode,messageTemplateIq['a']=uint8TypeCode,messageTemplateIq["stl"]=uint8TypeCode,messageTemplateIq['sc']=uint8TypeCode,messageTemplateIq['sd']=INT_TWO,messageTemplateIq['rt']=uint8TypeCode,messageTemplateIq['tog']=uint8TypeCode,messageTemplateIq['la']=float32TypeCode,messageTemplateIq['ja']=float32TypeCode,messageTemplateIq['sp']=float32TypeCode,messageTemplateIq['AUBAkIWQqEk']=INT_TWO;
// __UNIT__ u1923 [2083813,2083893) kind=expr len=184
messageTemplateIo['xJXXoGTVwzq']=INT_ONE,messageTemplateIo["JoHdvmpcMvL"]=float32TypeCode,messageTemplateIo['uBHZYKAHa']=float32TypeCode,messageTemplateIo['yxEKoSFAg']=float32TypeCode;
// __UNIT__ u2317 [2497719,2498655) kind=expr len=1574
partyController['SsysxYnEEx']=function(){var ayt=stringDecoderAlias;if(loadedPlayerRigCount<0x4){console['log']("Didn't load all players");return;}if(crazyGamesGame==undefined||!![]){startMatchmaking();return;}if(matchmakingActive)return;crazyGamesGame['addEventListener']("adStarted",muteVolumeForAd),crazyGamesGame["addEventListener"]('adFinished',handleAdFinished),crazyGamesGame['addEventListener']("adError",handleAdFinished),crazyGamesGame["requestAd"]('midga'+'me');},partyController["qaIlQNxrHk"]=function(){var ayu=stringDecoderAlias,a3l=bitsetDefinitions[liveKeyState['name']];for(var a3m=0x0;a3m<a3l["length"];a3m++){if(movementKeyNames["indexOf"](a3l[a3m])!=-0x1)continue;liveKeyState[a3l[a3m]]=![];}if(localWeaponRig==undefined)return![];for(var a3m=0x0;a3m<0x3;a3m++){if(weaponModelSlots[a3m]==undefined)return![];}return templatesLive['B20L372s8']['v']=0x64,templatesLive["B20L372s8"]['eXABYtRfN']=partyController["MqaFuSJOX"],templatesLive['B20L372s8']["afCJVYrCGK"]=!![],networkSendEnabled&&gameWebSocket!=null&&gameWebSocket['readyState']==0x1&&(encodeMessage(templatesLive["B20L372s8"],classSelectPacketView),gameWebSocket['send'](classSelectPacketBuffer)),classSelectScene['ReDNKHkwk']=![],classSelectScene['tGTnWzZUhv']=![],adsZoomInterpolator['t']=0x1,adsZoomInterpolator["TlGcAtEMrJ"]=adsZoomMin,adsZoomInterpolator['yYemIMQjxq']=adsZoomMin,currentAimSensitivity=aimSensitivityUnit*baseAimSensitivity,worldCamera['cGKveZTJVJM']+=0.01,partyController['ybKMeoEjyk']=![],mobileFireHeld=![],leftShootHeld=![],rightShootHeld=![],ignoreNextTouch=![],!![];};
// __UNIT__ u2476 [2545493,2546213) kind=function len=941
function initEffectPositionTracking(targetEntity){var azJ=stringDecoderAlias;targetEntity["zkT2rWLY297"]=new usvzFuAsEB['gURkzCzeY'](),targetEntity["b152tm12ro9"]=new usvzFuAsEB['gURkzCzeY'](),targetEntity['yoghpvfQE']=new usvzFuAsEB['gURkzCzeY'](),targetEntity['setPosition']=function(a3p){var azI=decodeString;targetEntity["position"]['copy'](a3p),targetEntity["zkT2rWLY297"]["copy"](a3p),targetEntity["b152tm12ro9"]['copy'](a3p);},targetEntity["positionFromArray"]=function(a3p){targetEntity['position']['fromArray'](a3p),targetEntity['setPosition'](targetEntity['position']);},targetEntity['NGSMBcCHUv']=function(a3p,a3q){var azK=azJ;targetEntity["position"]['setComponent'](a3p,targetEntity['position']["getComponent"](a3p)+a3q),targetEntity["zkT2rWLY297"]["setComponent"](a3p,targetEntity["zkT2rWLY297"]['getComponent'](a3p)+a3q),targetEntity["b152tm12ro9"]['setComponent'](a3p,targetEntity["b152tm12ro9"]['getComponent'](a3p)+a3q);};}
